### ISSUE TITLE
👌 IMPROVE: select primitive cell in `StructureSelectionStep`

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#63] opened 2021-06-07 07:09 UTC
After querying for e.g. Al in the following example:

<img width="1208" alt="Screenshot 2021-06-07 at 08 54 08" src="https://user-images.githubusercontent.com/25607960/120972329-ed357b80-c76d-11eb-8d51-1422eb51d360.png">

I am happy with the structure I found, but want to take the primitive (instead of conventional) unit cell to run the calculations, since this represents the same structure but requires fewer resources. However, that doesn't seem to be an option? I'd remove this "Camera type" selector and instead allow the user to switch between the conventional and unit cell. 

One way to do this would be to rely on `pymatgen`'s `SpaceGroupAnalyzer`:

https://pymatgen.org/pymatgen.symmetry.analyzer.html#pymatgen.symmetry.analyzer.SpacegroupAnalyzer

**Comment by yakutovicha** [comment] 2021-10-04 11:14
Related: https://github.com/aiidalab/aiidalab-widgets-base/issues/212

**Comment by unkcpz** [comment] 2021-11-09 16:36
I personally always feel that `pymatgen` is too big for such a simple task, and inside its actual implementation the pymatgen calls `spglib` to get the primitive cell or the conventional cell. `spglib` might be more lightweight for this.

To me, the problem is always where to put such simple primitive to conventional cell methods. 
I prefer that we have a the it implemented in the QeApp for the `StructureData` at the moment. 
I believe the similar functionality will be isolated into the  'material science specified data types' once we have that done.

**Comment by unkcpz** [comment] 2022-02-14 15:56
Related and re-addressed in #198

**Comment by unkcpz** [comment] 2022-11-24 17:35
closed by #216

**Closed by unkcpz** 2022-11-24 17:35 UTC
Labels: enhancement, topic/ui, priority/nice-to-have
