### ISSUE TITLE
Bug report: Application crashed with ValidationError

### ISSUE THREAD

**Issue by cpignedoli** [aiidalab/aiidalab-qe#365] opened 2023-03-13 12:40 UTC
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments (optional):

I was trying to setup euler.ethz.ch as computer
## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
ValidationError                           Traceback (most recent call last)
~/.local/lib/python3.9/site-packages/aiidalab_widgets_base/computational_resources.py in on_setup_computer(self, _)
    907             return False
    908         else:
--> 909             computer.store()
    910 
    911         # Callbacks will not run if the computer is not stored

/opt/conda/lib/python3.9/site-packages/aiida/orm/computers.py in store(self)
    286         are to be changed (e.g. a new mpirun command, etc.)
    287         """
--> 288         self.validate()
    289         return super().store()
    290 

/opt/conda/lib/python3.9/site-packages/aiida/orm/computers.py in validate(self)
    237         self._transport_type_validator(self.transport_type)
    238         self._scheduler_type_validator(self.scheduler_type)
--> 239         self._workdir_validator(self.get_workdir())
    240         self.default_memory_per_machine_validator(self.get_default_memory_per_machine())
    241 

/opt/conda/lib/python3.9/site-packages/aiida/orm/computers.py in _workdir_validator(cls, workdir)
    182         """
    183         if not workdir.strip():
--> 184             raise exceptions.ValidationError('No workdir specified')
    185 
    186         try:

ValidationError: No workdir specified
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNptWF1v47gV_SuB-7oyLMl24rxt8zaYadNmuoOiKAJKomXGEsmIVBxlMf-994uysl3kyYcUeT_OPfcyv6_e9BCMs6v7_JeV71Q8
uqFf3f--UkN9MlHXcRz06v4_q_22MnH1y2r1X9g3xZOzz_Onq3J9WOclrF6hv-Q3T98eb76P-ubLaG-K8iYv7nd39_nm5l_fH26K
TbFZ_YSjVH1WrQ50pTGNymqHF66KNfzBiQL64kzgZr2pNjPcqjEEo6wsFf-3kDUqqjh5vGC1We_W-
bzFKuvAv1Ome69gNcez1fVsH_TYuLQww6-jsnHsdfCDDgHXt2DpvP48-nZQjabr8iveqQqNLNb5ZzDTnZW9xRI-uV7_-Qf9EcIRa
nYoV5_WXumbcmkQw9nFDef6pIz90w0X07Q6hqxSQc9h5lC5zJszxme_vpPoAUNeKeklA53uK1NTpGSLDaY4xb4TjO6yk3H01Z73e
N-YIdCO7XrLSO8kcvINcvBNZ17FE8FbDtLQ8s9in347W2T18WjQ-Bzs2nyGs8rYxtg28Lp4T75CLAo2KMToztoGCcAdYZOts1ZbP
ajoBjI2p29jJNvxWzrsr6rSHX2Zb9ZYCRUQu1Zdx4bSHoS8G2JYH0dbR-e6kHXDmNWqPmk6e0-BqOph8pFtIwcrrcZojmMX3Oi3R
DlgBRpddXAm27HnOzoNpwGyAxd4h7Fnzabv8Df4eCJDt2zn4GJn_ER23tIZD2jPg7NxcGx-
jiyEBTKU7Bbabwm8xoL9rOvOVHThLf7SA9hOmdlguIorKrfmZIikD_ziKgW2DkHHzALdVGc-
yAcMNy_q3tijkxMOfK8Z6lHqggkEhlB47tId-BsUxh5Nmx1Nx2TbX_dmwRtr6Sq0i3Jdu84NqlfCwB1BtlHsslyNQCZilp2UbSDs
Lbkzb4A7XfUiqbljLLpxIB9QZCguIHSZsX6MWQo0VkORltwYP6_t-HhkjAPl8Sc8rTyIZtVT3SVvmKiNqkHWhW0MRFV3KgTRSLSs
0dXYil17ilyjQZelBnaShEYfx6Cb974T8jAIwgic4C6QyqMxAWyvXqCfhMgCn-Le2MD9hLZz6TZjdzG1FDkrowaV0TaKFBTgN5ql
e2W67A340cwFyqqk-x7IU6e7yjsiK5wAkXLGRnaWsPdae7S3HaC8mIJkhX7XNdSd5JF9PoJMKG-YdbwNoZfgbEBSKnaahQkZ1jli
YCk8OHYmPotVpYTsCDy4VlXJ1D2O3HmZzOgrZffNfHBUuLrbQWvb6SgW4rbT2Ct7HIwGDlIGmQkEQxXRHRx501hFZmAUTI_SBIWb
QdwUkiLpzOdV6HrA2ZrIsoOCxyuhkEFiLAngHp3fMNj7TsqzYEDSfLsuy7QHIVRYCLQwupiXwDlB5HvpU3TE7R_ATL9H8Fk3i2yZ
GBplWw2JDcJG_OhFNyZFFrd9MfZFFRQK2QDp3InpO_lNrBERKgUb9JENlN8zBVKHfRnBDT08g7gA9dh1PjEtMBVmQRc8C3p4E9XO
D59WIlUC0HgxYsjaaazo7s0S5MkDkkyVfQUzP7VYUWER4uvq82xAgYL8eTG75iFF-mwu1yZyK0BwXXKCW3ynhjOoJOj6kBrLhuAI
RQi9v5beiycC2eoQRXQPDPSqr5ToEnuO5TULec5edK4dh3EhMd_UmQc5zhydsjjjG1jVuIuVMOUCjf5JHfXCol5F32G3rGSOKT-
BINsg-mny2-OaCXG06QgMQA-lPqVWeCC3emBABpI8JAkATm7Jrt5nSWrKDbGm9z3rH7pCJoXW8wSQpxvGLprG1JFqUbDJT1weOJy
HxUxrVQxQ2HQr58JW1AxonkvtDjHhb5oRAHIWksucZmNshY8HFUkZeMqzOsSMpijDGdhRYKyOOJC-M1sRaLs3oy_CXowrDueVc2d
yA5JSLLAsnEy_oL8deyFFwelzMC-dUp7YOAcS38-DOWtswrLZPclLjonhbs7yX7C2eph1Y1RVp2X-3RDY604tggrAq190Mw_jgAr
ifimAq4G2kPWE80aYMwxxtUi1gdXiZArgb-MpeF0vezpi14mAJczrwTjkgVibS0a8foevI2kOR8G3YRQNoAtgDOp0gOlLS76RAo-
m6xzm57Bmcj4a4UMu5xrPAxFTzp9bVPRnbBcgAs9W9Tp1Z7pUnpryBkiaRaU08YwhweskuTQJkIFeHfvUKRTdPcBrKZ70GLIFUXP
mAi56npjOJiaG0UpAE-ky7lA-TLXzbUHxP_BlAuELQpHmzivwrBwcNMKwKAsPPTvTMI8sRNVPFcgbAxK76cEc__mDcsAV5uGWoKJ
oVsnILJRwTs7QOHRUcFuekf0E7S3K2yvnPvR4lfUiBfFx-vLju4xNZOYEZQpN98p4uuBx-jY9_eOrNL6SkL-
ph25J0envXtunp6_8jpSsTWgqVwpiVD0TICHOyeBO-zg9gWAz52_FBZoAYODQko1C5l1Zwb6agaS3EopN-
sy91Kr3CxnAiUExVXimAeCDXczFm3__-u0rCyMtf9BDFrNCh8I7OZVRIa4NuqXc0Rm5vAgG_TqCsPG-gj1L2PyawxDeLRd6J0ItE
9lwrMvD3a1UBW0dUUrWk5KJOr_lvCzwtbytkFz7eSnDpSy9SjbYse_wilCb1C35zqD12acWcqBG_QRDU_F9UOG0eK3Dw2v0KRb7n
XTFcIJeMY6mEbGjR2Ew73wDBzVYAw85J14RAlN1MPpNiyQWa-9CpE99m16K8DXWAbDv1w6HqClNDbQPXijnTGbS9F8cAAdUY72sr
BAHkLwMQ1uWBy5MhKfUIGTMAlUcceoQYaWsAlfxbTRJM6RteoBnpmpcUjraZ-xUh1Aspp_oUsa4BvG3WbAVI_mxnHjgrSLH8kshv
jY9T-YcaSCyiR2PWDtRXMCgf0fp4BsZgPGfWw202ChFumUMivH5U8ffplNoDWaVIG0g_bNlxEKj67jSR4tvdAUyb3SQ2RhjOfojV
Ekmu9NwD8J0falL7krGIcUlN-c9M-Y3BY-JadGrLirWp8a1KYTow6WGIVP-7VMQNy66oqe4jJ0FQ9rC4Cj_2knUADhAseH7L7WDX
Cj8Qw_nDz22i9fA5aQ1Z69kSeLpNqugSwdsSIt3Ni89_7G5lqJAMhfbag794j9eF3i_yUONbYGH8_xgIGZiwCY1pH-
boXEfxvv5-fjz5_8Axv8e8w==</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by unkcpz** [comment] 2023-11-08 22:58
We have a new computer/code setup widget, I assume the issue is solved? For `euler.ethz.ch` I think maybe it is worth to add to https://github.com/aiidateam/aiida-resource-registry so users who has access to the cluster can use it easily in aiidalab. 
The documentation of how to write a template in `resource-registry` is missing but those are computer/code setup config like file, we provide the examples for CSCS daint and Merlin in PSI, I hope it is easy to follow.
I'll close this issue for the moment, please fell free to reopen it if the same issue appears again.

**Closed by unkcpz** 2023-11-08 22:58 UTC
Labels: bug, automated-report
