### ISSUE TITLE
Bug report: Application crashed with InvalidRequestError

### ISSUE THREAD

**Issue by cpignedoli** [aiidalab/aiidalab-qe#803] opened 2024-09-23 07:44 UTC
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments (optional):

In the demo server i clicked the link "inspect" for a job in the joblist

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
/opt/conda/lib/python3.9/site-packages/sqlalchemy/orm/session.py in execute(self, statement, params, execution_options, bind_arguments, _parent_execute_state, _add_event)
   2360 
   2361         """
-> 2362         return self._execute_internal(
   2363             statement,
   2364             params,

/opt/conda/lib/python3.9/site-packages/sqlalchemy/orm/session.py in _execute_internal(self, statement, params, execution_options, bind_arguments, _parent_execute_state, _add_event, _scalar_result)
   2235         bind = self.get_bind(**bind_arguments)
   2236 
-> 2237         conn = self._connection_for_bind(bind)
   2238 
   2239         if _scalar_result and not compile_state_cls:

/opt/conda/lib/python3.9/site-packages/sqlalchemy/orm/session.py in _connection_for_bind(self, engine, execution_options, **kw)
   2104         if trans is None:
   2105             trans = self._autobegin_t()
-> 2106         return trans._connection_for_bind(engine, execution_options)
   2107 
   2108     @overload

/opt/conda/lib/python3.9/site-packages/sqlalchemy/orm/session.py in _connection_for_bind(self, bind, execution_options)

/opt/conda/lib/python3.9/site-packages/sqlalchemy/orm/state_changes.py in _go(fn, self, *arg, **kw)
    101                 and current_state not in prerequisite_state_collection
    102             ):
--> 103                 self._raise_for_prerequisite_state(fn.__name__, current_state)
    104 
    105             next_state = self._next_state

/opt/conda/lib/python3.9/site-packages/sqlalchemy/orm/session.py in _raise_for_prerequisite_state(self, operation_name, state)
    994             )
    995         else:
--> 996             raise sa_exc.InvalidRequestError(
    997                 f"This session is in '{state.name.lower()}' state; no "
    998                 "further SQL can be emitted within this transaction."

InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNptWNuO47gR_ZWG87oSLMmXcb9N5m0xk0zSs1kEQWBQEi2zTZFskmq3ejH_nmJVyWYv8uhDiqzrqUP_sXqVPihrVo_VLyunRTxZ
P64e_1gJ351VlF2cvFw9_me127Qqrn5Zrf4L--Z4tuZ4-3TVlIeyamD1Dv3l07r4rZ1MnB6evn1_-DHJh8_T8LB7qA6P9f6xqR9
--_HloV7Xm9VPOFF0FzHIgDcr1Yuis-neVV3uyhoOJvA8O-lfJjmlpXVZl-
vbkgty6i3AVbnN4JdJgAmjDM7LENL6Bk68rWvRpks2YH-
OHc92lP934YXhal2uRZWvXFU_yBiOrQhkeAM7yHRbOHURAO7KTyV9BFF-wcA1BGg5tqpD83mLMTaKKPsigtMB_d2TLSao-hxHjbs
PFB4zK4vn7ehr53rlA-7YlBtCRttT3D7ROSnDr7JwIp4R3tBRfrCmLrrTSSU3quTHR7holemVGQKtcxbQ66asazIgxGgv0uCeEq5
EbDbdcZBGehGtR-
Mq_DZGtDV9i4f9VbRS45cQ51RXLdRHJ7TO0p4gZ30M5WkyXbRWh0L7qehEd5Z49g4dbzs_u4iJ5w-lmKI6TTrYyW1woarQ6FZL-
BgQqCAGlLlIsnSbfoNLZ7RrQ2Z5G7Vyc5adL-n6L9ZEb8naijKMZqGVbMoGwcVz2ITR76QH2zDy0BqQqWa9oHwNxZfTA3Zv6fdZ-
CBjYaCwhFbvaHQKJy4q301UQhXlvtOquwAAtVbul99FcMoY_HJdcmo6q60Xo-AC2SJkekHZouZAoOAWLs7C9BC2gauTN0Q7eXRgq
SfMih28cOcEN2AXhWTu9GICudrLdhr42x2GvZfADlxCW_axl6cpyP5t1JwMAqHtIchESUt19SpcjrZ9BnILkWimWpZMIHJj6sFDb
BeiB4-OLsWYbdullUlfVUfNw3UvoZGlidxTG-YiOQqlj6-QmJ7NrrkYYS8EwioTKT8pBPKtky7ZPHioULSuxuKQb7KD0uXYkt8n6
LTnYE2A8sI0gR1EmSelpbaY5iZhuFureGRqbThIJ8jOvTC3VK6niYgf7lmjocBtBXMSWMbFhPdgDl_VO4WB-nXwUhotIxuaoPM0C
nPySkJ5YDLpXNUbgcYkz9WYOlqrthhlFBArIs1l620VuBzqqUNa3N6W3Qy9apA4dslhBi3EchR9PjLULcn7stnkUAH0BCHW4U-7w
R9GakKY7vGIPRl_Awv5FsFN2Wd5UjH0wgwSUhqy_D_LXi2Nmbb9qswzTA1MGV71bIGEWiZyBCDZW_zkgO34Ifmbxe_nCYyW_giND
SVGjtL2ZYGK4MZ9jBdQ4K_MeNXhw0rE2oZy5dxn15ynFk1e5yDNVkgskv8dLNw8pB4JWUDvq8ebAXXitj8t3qNeLQx1Udc7A-8ZC
FYvXmwQ1MJfsk4CoQNdBvOwy-yGOI9ibAVzDRHrN3Gx_GGqYtzwYdlfenslEbRnYHJP4iQzAh5FdDqNipbFUv0BLJQBxpQc18Qso
wpxMpKHZ6quEbp0XsbCnsbC6EbimYVUxzAkGs4IbZx0VL3qIjUFYqbttAgB5cZC6gnjSlkmGUDWQBSpeojeTJv0oYjYd0QpRgZgh
jTa1SK_dgjHq_WXNxIFtHPQr0peOeKpKIBOZGvtBY2DUqwzrAhnNWalZqaRE1PTYLcwxs9LSOmGrNUTbyU7aCwRZ9bERA7UVowCp
j0rMAJHqUVGeAC8uEXI4W-Yckvr1gzYDlgWajNkwhOmhBgVVk2dZhhjKD6T9sLb5JuTHakSmshuCBM3RHLOwTzWMsBUl5ySLaJa2
yuRJ9HWd8U5q_FY5Uieon2XITHZMZEldMPRiFFyrWDjLGqfhSIoGgpYqskZE5x0LiIceriF5ILDDXAOLnsQy_Esp1BkNVTxt7DoY
pHmy0VFTn2DKyFZh_dQP7gwd9YNNcbtUB4yKClOgcRzWwFV7C1MgFwZOxhZhYQxmzGLm1todQI4ZPMXdfrn7-jyhlyGW4Igu0lhA
HIb9nBORdDkNfbChnrfzcDoEdsomZVDx9vzpeby4gXg1xgX7VwSv32_82Gd5CIZ-
evvP3gPujZD18FsugvDA-76Nj_94ytPgwaRv4kvOq_G-e9Omqenr7m-dnPyjpoiJQQjOgMS4i1_NI--
z08gIai89-wizkkYzpITWIM1dbYCDWxeuZOyL9KgKrQdBo7qbdELKi7SAAC8k5cVe_Tvz9--IkOs-
Zp3fDuldOIRL7JY9MsyVr2EV2LgkDZE3QuWvRCINfyUer-cBWvHak8Zz_CyI6JJVbW7LRVpqVj08DrNq0_p9tAppioW_0HKi1uo-
oAtFORIE6pht55AMdQ_vAhnfgXiSTJObnFuty2pqcIZdNA0qX4JcnIvqDe6kgRAMAqeCDYbDum5E5R8XV6ndelsiHieG8i9pdqgp
j7rpClmzlSTMhMicGnBqmzNAzDM493XZAcQ65TGKxdlOg7qQXQKx9eB2RU4c4Se7i2raQKVmbsQ6kw2RbskhaKUfqusfFJs3pfXA
p5hPR9LKji-9CO9-il2UG0qatIQ28W-2SV5j6otsLpN04gOeGePse_SEVOq5Fx5wvsTxqQAKlYoSRvmnsmdjtEeefsi2IBF7s80l
igN4ZCFZhlxyK3_EiB550xsX0Xszr0d0EIKwbUDVcRP-BpvuMpWGlA3zDNLqgAO0Mwg5G88XXFFXc9SUpwb6nISWkcnvbJJPtymZ
ZUtB9PeYsZ_PqCN8CCIeS3Coyx7npAxs_BEU6w_35VzLI7Wq58__wfgGEPf</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by cpignedoli** [comment] 2024-09-25 12:49
https://github.com/user-attachments/assets/49ed756d-cfcd-4cdd-b831-ea037b554568

**Comment by superstar54** [comment] 2024-10-08 09:55
Hi @cpignedoli , thanks for the report and the video. It seems the issue is related to the SQL database. Maybe the database service is not ready when the machine has just been initialized.

However, in my test using the demo server and local installation, I can not reproduce this issue.

**Comment by cpignedoli** [comment] 2024-10-08 10:54
Hi @superstar54, yes, I also have the impression this occurs only if the server is not ready, so I would not investigate this further

**Comment by superstar54** [comment] 2024-10-08 11:17
Ok, I am closing this issue for now. If we encounter the problem more, I will investigate it further.

**Closed by superstar54** 2024-10-08 11:17 UTC
Labels: bug, automated-report
