### ISSUE TITLE
TraitError appears on COD selection

### ISSUE THREAD

**Issue by chrisjsewell** [aiidalab/aiidalab-qe#35] opened 2020-12-02 13:56 UTC
When selecting a structure from COD, I got the traceback below appear (this is on Quantum Mobile).
It didn't seem to actually affect anything though, since the structure still appeared and everything seemed to work fine:

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/2997570/100881651-7a8dcf80-34ae-11eb-9c63-0f54faaaae11.png">

```python
---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
~/.virtualenvs/aiida/lib/python3.7/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/.virtualenvs/aiida/lib/python3.7/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

/usr/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    117         if type is None:
    118             try:
--> 119                 next(self.gen)
    120             except StopIteration:
    121                 return False

~/.virtualenvs/aiida/lib/python3.7/site-packages/traitlets/traitlets.py in hold_trait_notifications(self)
   1203                                 self._trait_values.pop(name)
   1204                 cache = {}
-> 1205                 raise e
   1206             finally:
   1207                 self._cross_validation_lock = False

~/.virtualenvs/aiida/lib/python3.7/site-packages/traitlets/traitlets.py in hold_trait_notifications(self)
   1189                 for name in list(cache.keys()):
   1190                     trait = getattr(self.__class__, name)
-> 1191                     value = trait._cross_validate(self, getattr(self, name))
   1192                     self.set_trait(name, value)
   1193             except TraitError as e:

~/.virtualenvs/aiida/lib/python3.7/site-packages/traitlets/traitlets.py in _cross_validate(self, obj, value)
    616         if self.name in obj._trait_validators:
    617             proposal = Bunch({'trait': self, 'value': value, 'owner': obj})
--> 618             value = obj._trait_validators[self.name](obj, proposal)
    619         elif hasattr(obj, '_%s_validate' % self.name):
    620             meth_name = '_%s_validate' % self.name

~/.virtualenvs/aiida/lib/python3.7/site-packages/traitlets/traitlets.py in __call__(self, *args, **kwargs)
    973         """Pass `*args` and `**kwargs` to the handler's function if it exists."""
    974         if hasattr(self, 'func'):
--> 975             return self.func(*args, **kwargs)
    976         else:
    977             return self._init_call(*args, **kwargs)

~/.virtualenvs/aiida/lib/python3.7/site-packages/ipywidgets/widgets/widget_selection.py in _validate_index(self, proposal)
    223             return proposal.value
    224         else:
--> 225             raise TraitError('Invalid selection: index out of bounds')
    226 
    227     @observe('index')

TraitError: Invalid selection: index out of bounds
```

**Comment by csadorf** [comment] 2020-12-03 08:45
Thank you for reporting!

(And I have to say, the app looks really cool in dark mode. 🕶️ )

**Comment by csadorf** [comment] 2020-12-03 09:43
@chrisjsewell I just tested this on aiidalab-demo and aiidalab-tutorials with the latest release (v20.11.2) and the exact same search query and structure selection and was not able to reproduce the issue. Can you confirm that this still a problem?

**Comment by yakutovicha** [comment] 2021-10-04 00:18
The COD widget was removed recently from the app, so I am going to close the issue.

**Closed by yakutovicha** 2021-10-04 00:18 UTC
Labels: bug
