### ISSUE TITLE
Bug report: Application crashed with ValueError

### ISSUE THREAD

**Issue by cpignedoli** [aiidalab/aiidalab-qe#895] opened 2024-10-23 16:14 UTC
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments (optional):

_In the demo server I did bulk gold, primitive cell, with spin-orbit coupling. Once the calculation was completed, I went to the PDOS tab. Selecting "Orbitals" or "Angular momentum" results in the crash._

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
ValueError                                Traceback (most recent call last)
/opt/conda/lib/python3.9/site-packages/aiidalab_qe/common/bandpdoswidget.py in _update_plot(self, _)
    745                 clear_output(wait=True)
    746             else:
--> 747                 self.pdos_data = self._get_pdos_data()
    748                 self.bands_data = self._get_bands_data()
    749                 self.bandsplot_widget = BandPdosPlotly(

/opt/conda/lib/python3.9/site-packages/aiidalab_qe/common/bandpdoswidget.py in _get_pdos_data(self)
    703         )
    704         if syntax_ok:
--> 705             pdos = get_pdos_data(
    706                 self.pdos,
    707                 group_tag=self.dos_atoms_group.value,

/opt/conda/lib/python3.9/site-packages/aiidalab_qe/common/bandpdoswidget.py in get_pdos_data(pdos, group_tag, plot_tag, selected_atoms)
    977     # Updata labels if plot_tag is different than total
    978     if plot_tag != "total":
--> 979         data_dict = update_pdos_labels(data_dict)
    980     #    data_dict = deepcopy(new_dict)
    981 

/opt/conda/lib/python3.9/site-packages/aiidalab_qe/common/bandpdoswidget.py in update_pdos_labels(pdos_data)
   1443             - pdos_data (dict): Updated PDOS data with correct orbital labels.
   1444     """
-> 1445     original_labels, orbital_dict = get_labels_radial_nodes(pdos_data)
   1446     orbital_assignment = assign_orbital_labels(orbital_dict)
   1447     updated_labels = get_new_pdos_labels(original_labels, orbital_assignment)

/opt/conda/lib/python3.9/site-packages/aiidalab_qe/common/bandpdoswidget.py in get_labels_radial_nodes(pdos_dict)
   1309             continue  # Malformed label
   1310 
-> 1311         radial_node = int(radial_orbital[0][1:])  # Extract radial index from 'r#'
   1312         orbital = radial_orbital[1][0]  # Orbital type ('s', 'p', 'd', 'f')
   1313 

ValueError: invalid literal for int() with base 10: '=<sup>+1</sup>/<sub>2</sub>'
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNptWF1v67gR_SuB-7oSLMl2rvO2zdvipk2bu7soisKgJFpmTJGMSMVRFve_dzgztHkX--
hDipzPM4f-Y_UuJ6-sWT1UP62cFuFop3H18MdKTN1JBdmFeZKrh_-udptWhdVPq9X_YN8STtYcrp-umnJfVg2s3qC_famLX9vZhP
nu5en57smauxfp7uq7qnpodg_N5u7Xb4939brerL7DiaI7i0F6vFmpXhSdjfeu6nJX1nAwgafFyeltlnNcWpd1ub4uOS_n3gJcld
sMfpsFmDBK7ybpfVzfwIm39YswRslpv8a76r9aKS52Oh-1vXjc09z2aNFGaAPe59jhZEf5lwtvDFfrci3qfOWi-kEGf2iFl-ka3m
ELp84CwF35pawImsY3DHtDgJZjqzp0nrcYY4MIsi8ChMxjtO7JFuNVfQqjxt17Cq5ZlMXzdvS1c72aPO7YlBtCRttT1L_QObE-3m
XhRDghvKGjpsGauuiORxXdqFK4bnDRKtMrM3ha55Cj101Z12SAD8GepaGIw5WILaY7DNLISQQ7oXEVfhsC2hq_xcP-
Llqp8UuIc6zKFqqrE1pnRRMhZ6fgy-NsumCt9oWe5qIT3Uni2Tt0vO2mxQUsG_5Qijmo46y9nd0GF6oKjW61hI8BgfpjQJmzJEu3
8Te4dEK7NmTWZINWbsmy8xivf7QmTJasrSjDaBZayaZsEEyewyaMficnsA0jD40FmWrWCeVrKL6cHrB7S79PYvIyFAYKS2j1iUbH
cOKimrqZSqii3HdadWcAoNbK-_S78E4Zg1-uS05NZ7WdxCi4QLYImV5Qtqg5ECiYAIqTMD2EbeDq5A3BzhM6kOoJs2KHSbhThBuw
i0KydDqZQK72sp0H_naHYe8lcAuX0JZ97OVx9rL_GDUng0AgDQgyEVqqrl7588G2r0CNPhBJVWnJeKJG3E4Z7W3nwwQeHVyMMdu2
iyuzvqiOmofrXkIjSxO4pzbMZHIUSh_eITE9m52YCvZCIKwygfITQyA_OumizcMEFYrW1Vgc8kN2ULocW_L7CJ326q3xUF6YJrCD
CPeotNQW09xEDHdrFQ5MzA0H6QjZuRXmdkPgTGMD7lmjocBtBXMSWMbFhPdgDt_VJ4WB-nWYpDRaBjY0Qqd5FOY4KQnlgcmkc1Vv
BBoTPVdj7Git2mKUQUCsiDTT1usqTAKopw5pcXtddgv0qkHi2EWHGbQQy1H0-cBR1yTfl80mhwqgJwix9n_aDf4wUhPCdI9H3JPx
V7CQHwHclH2WJxV8L8wgIaU-y_-r7FVqzLjtF2VeYWpgyvCqVwsk1DKRIwDJ3uIne2zHH5K_SX6_zmC0nA7Q2FBi5ChtTwtUBFfu
Y7yAAn9nxqv2P6wErG0oV859ds1pbtHkdQ7SbIXEIvnfwMItQ-wRnwX0tnq4GlBHbvvT4i3qVWKos7rcGPieAW918mKDoBbTOesk
kEnQZTAPu8xuiPMoxlYw1xCxPomz5Q9jFeOGH5anc28vJKHuGZjdizjKjIBHEZyOo6JlqVX_ABbKAGNKjmtkllH5MBvJwzNW1whd
uqSxABVf47luJKJJrDr6IfJwxmjjrIPqVReoKxAzbaeF96g3EqtHjEsljTKArIEwUvkQv5k2yksRsPGIU4z0QA1xtquk3nYIhyi7
PkgV0M5Bvyt54ZDHqgA-ka21ZzQO_KozrPAnNWa1ZuaRM1PTZLcwx08ppnRD1uuRuKIdNJeINGuiIgdyKwQB454lGIGj1CJjPADe
XCYYHQw2kXq3YcB2QLNQnD7TrTAmxKiwbOo4xBhD7RrFF34rP5zsSJbQSHaDn7kjonMOBrKWHsa65JRsEdUgY-NdycpnxTmr8Vjl
SJ_GQLrzEKnsENkS2uFgxCi5VrBz0mOBlSJIGgpYLMoFE1zTMHCaQx_LDqvc4QY4B5cnUMvhJGdfZDVU8bew6EIRB8xZBU59gys-
Wof3UEM4v3TWDTXGbV_uMyhKToHMc10BWTxZGAG5NHYwswoJczajFre00OsEENU_L4_q-
O_f0eUNuQy3eEF2k8QA5Drta2o2gOZJYy9sqPndApQesI2iWTl0uL5-ai4vXgCCDSGJZ37IPN8IsY56kbBffv-GABfVAl0Hw-mmD
Pe462l5-ddXHgcNIv8QjzqvxuWfTpqXl6-5wHZL9I6aIiYEI7oA4sM1fzSQnpcX0BBU3vfsIg5KmM6SE1iDNXW2Ag1s3rmTsi_ip
Cq0HQaO6nVxElRcJAIA-CQvK_boPz8_fUWGWPM1n_h4iunEI95kkQRMmquThEem55A21K8Jy54IxBrTHHu_XASLx-
qeMp7hZUdEE6tqd10q4lKRBPE6Dqwv8XbfKaYqVv9eyrNLVL3HFvJypBHVsFsvIBnqb5PwJ34G4kkyzC45t9uW1FT-
BEJonlWfghzd8-qDrqSi8kbBG8FmwyG-d7yS7-l5WpfO-oDnuYHcS9UGNfWzjqJi4Uw1MTM-
AJcWLMvWPAH9Mt58jXYAsc5xvnJRxuOgHkSncH7tmbeAM0fo6d6ynCZQmaXzvs50U7ApKRSl-Ftl5RNj85meC3iGnfhYksHhrR_p
TwOKHVSbCppExDbZt7io71G2eZa3cRrRAZ_sMfZdROZYybn0hAcojEkBVKxQkzbMPbM7HoI98Pak2IBFbu801igN4ZCFJo045Nbf
BGjeJVPbFxG6U28HtJBCcOlAFvEbvsYbLrKVBuQN80xKFcAemhmU_JWnK66oy0lKinNDXU5K6-DkpGyUD9dpWWXL3rTXmPG_D2gj
vAhCXovwKsveJ2TMIiaiKRagn8o5Vkfr1ffv_wd3Elbk</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by edan-bainglass** [comment] 2024-12-10 07:38
Thanks @cpignedoli. @AndresOrtegaGuerrero could you take a look at this?

**Comment by AndresOrtegaGuerrero** [comment] 2024-12-22 11:12
@cpignedoli are you using the main (latest commit) branch ? I cannot reproduce your problem for Au with SOC .

**Comment by AndresOrtegaGuerrero** [comment] 2024-12-23 13:40
I will close this , the latest status of the app doesnt present this error

**Closed** 2024-12-23 13:40 UTC
Labels: bug, automated-report
