### ISSUE TITLE
Bug report: Application crashed with UnboundLocalError

### ISSUE THREAD

**Issue by mkotiuga** [aiidalab/aiidalab-qe#106] opened 2021-07-27 17:41 UTC
## Automated report

_This issue was created with the app's automated bug reporting feature.
Attached to this issue is the full traceback as well as an environment
fingerprint that contains information about the operating system as well as all
installed libraries._

## Additional comments (optional):

_Example: I submitted a calculation for Ca like pk 707, this one has pk 709 _

## Attachments

<details>
<summary>Traceback</summary>

```python-traceback
UnboundLocalError                         Traceback (most recent call last)
~/apps/quantum-espresso/aiidalab_qe/widgets.py in _observe_node(self, change)
    229                 clear_output()
    230                 if change["new"]:
--> 231                     display(viewer(change["new"]))
    232 
    233 

~/.local/lib/python3.7/site-packages/aiidalab_widgets_base/viewers.py in viewer(obj, downloadable, **kwargs)
     70     try:
     71         _viewer = AIIDA_VIEWER_MAPPING[obj.node_type]
---> 72         return _viewer(obj, downloadable=downloadable, **kwargs)
     73     except (KeyError) as exc:
     74         if obj.node_type in str(exc):

~/apps/quantum-espresso/aiidalab_qe/node_view.py in __init__(self, node, **kwargs)
    217             "Workflow Summary",
    218         ]
--> 219         self.result_children = [self.get_summary()]
    220         self.result_tabs = ipw.Tab()
    221 

~/apps/quantum-espresso/aiidalab_qe/node_view.py in get_summary(self)
    285 
    286     def get_summary(self):
--> 287         return SummaryView(self.node)
    288 
    289     def get_structure(self):

~/apps/quantum-espresso/aiidalab_qe/node_view.py in __init__(self, wc_node, **kwargs)
    177             return "Yes" if truthy else "No"
    178 
--> 179         report = generate_report_dict(self.wc_node)
    180 
    181         env = Environment()

~/apps/quantum-espresso/aiidalab_qe/report.py in generate_report_dict(qeapp_wc)
     96 def generate_report_dict(qeapp_wc):
     97     """Generate a dictionary for reporting the inputs for the `QeAppWorkChain`"""
---> 98     return dict(_generate_report_dict(qeapp_wc))
     99 
    100 

~/apps/quantum-espresso/aiidalab_qe/report.py in _generate_report_dict(qeapp_wc)
     84         bands_kpoints_distance = qeapp_wc.inputs.bands.bands_kpoints_distance.value
     85 
---> 86     energy_cutoff_wfc = round(pw_parameters["SYSTEM"]["ecutwfc"])
     87     energy_cutoff_rho = round(pw_parameters["SYSTEM"]["ecutrho"])
     88 

UnboundLocalError: local variable 'pw_parameters' referenced before assignment
```
</details>

<details>
<summary>Environment fingerprint</summary>
<pre>eNp9WF1v67gR_SuB-7oyLNmOk_u2zXYfipv27uZuF0VRFJREWbQpkSGpOMri_vcdzgxl5gYokhcffs-
cOTOjP1Yv0nllxtWn8oeV1SJ0xg2rT3-shGt6FWQTJidXn_6zut3VKqx-WK3-C_Pm0Jvxf8vS1XZ9WN_D4BX5S3nz9Pjl5uskbx7
FfFOWN9Xm037zaXO4-e3rA_yoytU32Ek0Z3GUHk9UqhVFLcbWF2r0Fs6GjTbr3XoDW_OoOrYdwdX6doEb0wZjNGyzqtZlNr8x8fa
rcn273l5BW50R3OYz3eyD0OUBNy_zTdpWNjj_Hai6DsEqAzstJ_cBPYrJeyVGHNity2VAi2GwHg-8y-ZrPxicu8nAUYwG3NEXcrA
Cl-S3NzaoQb3JDwazXk6tQfh2XS3ws3xOJ4jrfZ4nMYZpkN466b1Bx-6yVU54PPv980I9mFZq_-FSySURvVr_BTb54KeLGEcl3f0
GRzaZjWYx1OaDt96ksZZ9stxPizouL4GM2wwrpB7JqddtI_wsi4tx56YXilyzyUcvqj3K4IGPXiZTuYY2MIVV52iI28VvEDXPaK8
tHQJbCB-kw4MP6xIvqduTHGaE7nmaHGpF5Nqv7yIyKm_ubjclYPfJEKNXVR8GzUzGE61tlfNMqV1EYsC-
yMKK0HOA4GJ3NGNVNF2nonE2yezOmQsbEKfhK-
Hy92Q7P49NcZSjdCIYonSJ60LAU6vk6r-KWmr0Gj2phohuhNZ8hQ1C34c0GamGmLMBj-
WJahRuNg6YzkSOD6u1FE2fGbc2Z9njkcSr-tlqXlEChjs5E7SyM5sfoWmw1VWgSjbuA-
wtH8wYnNFpiygsTcTbwjpjpQszu6hKI4nbEB4M6qawMtu4abSq8fch_oJNFLugijvhNdkrYFt6atNBGEs-Cyf0wrUy4EEbRuSgxs
68e1ujXDNRqJUHOl2rJorcgQMEf4McDlbLQBbYpPfw0NipY9EpLVktNsuYt2ocmcvMg8Zo48QgMj_BDq3Am97TvvF3wQpf9EACrc
YjWSRNgCNNfQIMnktmN-asZDMFip0Uy8gUc3TC9nPGhGZudLoXmaeV9XS0cyYYIN4mkXjHctZKaVnA92zpVnaTl-3roFPIIghK2A
g2WJKsn05iPBoE4A8XA7cxJ2azWgOvUCyAJZm6nfRFNRye8B-fJkED5Bg4bOOWiA5CadBKDXK0BCCNAFVna9QYWFsjFuSWwheP6U
B6hFXkR7LCz1r4M--yS7-LB4PBvI2UXWYVv_7t6Ws3aY7UmNc736zlqzUuZOofwb7t9oUyGe27iSqG-Og7vA167UW9ERad3O9t8m
LcqJ8GMXZOSWDIjLoXl6l2FGTOOEcNsUygDJcuoIZ4I4iyYpBBgJ0E2YAuch2FZGYm18QqA9zNa0dF9Ms0EPQibsLKz8G9oYGzdC
PqHMQFXW9xOJB5n6ZFKMrm1fPLDsFJmekyINeDDlyfXMFCvgawh2yzwkMF3wLzpDOTz-CTbFWyd_z9dzWeREWmI8qcEClYW9KdTq
ZOCkUWO3kzZsdiECTcR90RmVafJniSdAUoBDASDVNSmltGqPbacSwxHHOrnY-R8hwa6-r96NUsqQI6q8tVy3cMeKNfWCNIDLRwZ5
Ab55Mi0OO1ac6LqpWk1prCfMdmfxRnk8XGI2zUmsvIFE3QZJ9EJzO-DMI3KqtydkTVQYSYj8i2Wy74riAkQtBBmb19iBbXUr5kij
4oHyaedYdXGCBHzSl_UOIbwMIFFOku3eGO65HBDiQnJbNt8McoxGxTPHTSQbUKE_KemTTWizdjctgSZEawc2DqHxCLTYJIK3Ga9K
HAooHFYMdwePjp5x0ntAMhseh6RXru8W7jUb8oeWEdwmVQ6daQCPBMqmZHyN6k6hXd1Wi5eHUXRQVLYNGyYcnqCbuylLNvvIqBzO
ogxfslv0a7UL6iRAUSfY8Q5Mwgai0z0bJieLZchNBvyHY-
yzsRMA3cEfzjM5sAQ8WgzpQ_DnwmkHapiykYI2bY_TQn9MCeio-8ZejKPuKSrR26hdI3lC7KRCfz5csFf-VabMeMsUc_ZdpgIe1r
6aH6kEzKPaBflNZYNd5xyH1RTJbyli6tLFXgxApk_IynlPx4PR2PFMklbQHIwLENtSeebWbDDMSfzoC893LyRcZObtDioA0Yg2cV
UiqLhbT1UYPRFvxCPzfGHquCqky04x3ZMcywD-QHnwUgs43LCjs3QjmidkUO-
jI_qO7X37mq2NIk40Xg8omRRZC4VIg5Zgxc87NrMe1AldWr8bWApw6pj6M9IEtpGZgL1vhAxy8aGt-
Bppz7CQvvahPrDcYUFAM5_WaIXMhQFAtUMeN2j_PTL5-5NyHkH-JB80q6-T-tHJ-ePlNkME3n-EAOF5h4QAwQaH6Sqw58sB8gYH2
WcL7MTyDOnus82i5IT1pToepxSgUDSfZntVgNRyD5pfpok68Y5EAlPInP_XXEAwdVN3PRmbaC7HzyeTzPwZwaMVgOLsacmLMOBoA
3sney2b9_fPzMukg7v2FfWFUsbdB0Xr9UYEsZp8Hhsapj9SDkeQJL0LyKhDJhBT4sq-CdhMWptqbU4CYxSB27Z12kwhzL0LvNMrq
Oo0v4foevuX3ZcIMDqQ4irIBezFHzUO0SzqFClPdS1IanlJQnvZRnm_LRPVLkCVJe9dUJ32fOByGe7NJY3UetQrpHzd6UmxjVvpc
6dhG9GDJm-h4qvWlSbcYtr2KrE0sXKgpJab16pbAmbfGjudTQrAJZh4GjlFzt7TEVR6xtTxieXAHhCRSvICpzDf0K91Rkfh6DRNa
ZaYQ2EqrXrK_gYUgR6bsJOZLwJnajUChAj68lPNhmafv9DGgNoU3wRaugTQnQ_Wdk_X7my__dKX5e4AkVV13vJ5z8UlJssjek4ee
Qbb_9MAwSqKCXeYuuSx8ySswpNA_KTijT4Rmi61KNijz55fOPOpaeS2zs3qHFb0uhvb3FDyj-WaPkpoosQkG4mMFlyjtR9P1Us-h
vK3TqHtXDz6nOiJtB3py0CKkMiyIC2Rz6b8Hf1LjXiKK1fHchaoX4pGlUsf1sKfdGs0ShEa0FkjdBc7-H000KRfIOaBofQuwLz-2
AqWbPv51QQac2hUiHGOQy6bM-A36D0amdiJ8-fOqRyMnhDepjQTeJ06cxfqkQkNeV5Knopsl2IFwFx1PKEZODaKy3lBYp_v8loO2
as4rkxWiI6smk7xN0zkWEpm_NMb052v7SQOm_fLyKp15kLUewH7wghUlc_Lt05zc5HTM2XnopdeJBPJa6CPqcvHweolzHQ98XRxU
_lfuPsV5sxvzAc6CZpXRa0vOgk1h6o6iB8SEz8C2TxDeF3yqpFfj27U8BMaRK</pre>
</details>

**By submitting this issue I confirm that I am aware that this information can
potentially be used to determine what kind of calculation was performed at the
time of error.**

**Comment by csadorf** [comment] 2021-07-28 07:26
Thx for reporting! Closing as duplicate of #101 .

**Closed by csadorf** 2021-07-28 07:26 UTC
Labels: automated-report, bug, duplicate
